#!/usr/bin/env python3
"""
Master Control — project structure & wiring verifier.

The offline harness cannot type-check Android/Compose code (that needs the
Android SDK plus Google Maven artifacts), so this verifier statically checks the
things that most often break a multi-module Gradle build:

  1. Every module referenced in settings.gradle.kts exists and has a build file;
     every Android module has a manifest; every directory module is included.
  2. Every `project(":x")` dependency points at a real module.
  3. Every project import (`com.mastercontrol.app.…`) resolves to a declaration
     that actually exists in the repository.
  4. Every project import resolves through the *declared* Gradle dependency
     graph (following `api` transitively). This catches the classic
     "compiles in the IDE, fails in Gradle" missing-dependency bug.
  5. Hilt wiring: every `@Binds`/`@Provides` implementation type exists, every
     injected interface has a binding, every `@HiltViewModel` dependency is
     either bound or `@Inject`-constructible.
  6. Production-quality rules from the specification: no TODO/FIXME/
     NotImplementedException/placeholder/mock wiring in production sources.
  7. Required documentation, licence and CI files exist.
  8. Every Material icon used in the UI is listed in
     tools/verify/icons-allowlist.txt, so the icon set stays reviewable for
     accessibility (icon + word pairing) and APK size.

Exit code 0 = clean, 1 = problems found, 2 = verifier misconfigured.
"""

from __future__ import annotations

import os
import re
import sys
from collections import defaultdict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PROJECT_PACKAGE = "com.mastercontrol.app"

# Generated by AGP at build time; never present as a Kotlin source declaration.
GENERATED_CLASSES = {"R", "BuildConfig", "Manifest", "DataBinderMapperImpl"}

# Imports that are consumed by the compiler rather than by an explicit name in
# the source: property delegates (`by remember { … }`, `by collectAsState…`).
IMPLICIT_IMPORTS = {
    "getValue", "setValue", "provideDelegate", "collectAsState",
    "observeAsState", "component1", "component2", "component3", "component4",
    "component5", "contains", "rangeTo", "plus", "iterator",
}

# Modules that hold JVM-only Kotlin (`kotlin("jvm")`) have no Android manifest.
ANDROID_MANIFEST_REQUIRED = True

DECL_TYPE_RE = re.compile(
    r"^\s*(?:(?:public|internal|private|protected|abstract|open|sealed|data|value|enum|annotation|inner|expect|actual|fun)\s+)*"
    r"(class|interface|object)\s+([A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)
DECL_FUN_RE = re.compile(r"^\s*(?:(?:public|internal|private|protected|open|override|suspend|inline|operator|infix|external|expect|actual|tailrec)\s+)*fun\s+(?:<[^>]*>\s*)?(?:([A-Za-z_][A-Za-z0-9_.]*)\.)?([A-Za-z_][A-Za-z0-9_]*)\s*[(<]")
DECL_PROP_RE = re.compile(r"^\s*(?:(?:public|internal|private|protected|open|override|const|lateinit)\s+)*val\s+(?:([A-Za-z_][A-Za-z0-9_.]*)\.)?([A-Za-z_][A-Za-z0-9_]*)")
DECL_VAR_RE = DECL_PROP_RE  # only val is collected; var is rare at top level
DECL_TYPEALIAS_RE = re.compile(r"^\s*typealias\s+([A-Za-z_][A-Za-z0-9_]*)")
PACKAGE_RE = re.compile(r"^\s*package\s+([A-Za-z0-9_.]+)")
IMPORT_RE = re.compile(r"^\s*import\s+([A-Za-z0-9_.]+)(?:\s+as\s+[A-Za-z0-9_]+)?\s*$")

BANNED_PATTERNS = [
    (r"\bTODO\b", "TODO in production source"),
    (r"\bFIXME\b", "FIXME in production source"),
    (r"\bXXX\b", "XXX marker in production source"),
    (r"NotImplementedError", "NotImplementedError in production source"),
    (r"\bnot implemented\b", "'not implemented' in production source"),
    (r"\bNotImplemented\b", "NotImplemented in production source"),
    (r"\bfake (?:progress|upload|repository|service|data)\b", "fake implementation wording"),
    (r"\bplaceholder button\b", "placeholder button"),
    (r"\bsample (?:video|channel|movie|data)\b", "hardcoded sample data"),
    (r"\bmock(?:ed)? (?:telegram|upload|repository)\b", "mocked production dependency"),
]

REQUIRED_FILES = [
    "README.md",
    "ARCHITECTURE.md",
    "SETUP.md",
    "BUILD.md",
    "SECURITY.md",
    "TELEGRAM_SETUP.md",
    "THIRD_PARTY_LICENSES.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "NOTICE",
    ".github/workflows/ci.yml",
    "app/src/main/AndroidManifest.xml",
    "scripts/build-tdlib.sh",
]


ICONS_ALLOWLIST = os.path.join(ROOT, "tools", "verify", "icons-allowlist.txt")


class Problem:
    def __init__(self, severity: str, where: str, message: str):
        self.severity = severity
        self.where = where
        self.message = message

    def __str__(self) -> str:
        return f"{self.severity}: {self.where}: {self.message}"


def read(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        return handle.read()


def strip_block_comments(text: str) -> str:
    """Remove /* … */ comments so commented-out code does not confuse the scan."""
    return re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)


def strip_line_comments(line: str) -> str:
    return re.sub(r"(^|\s)//.*$", "", line)


def parse_modules() -> tuple[list[str], dict[str, str]]:
    settings = read(os.path.join(ROOT, "settings.gradle.kts"))
    includes = re.findall(r'include\(\s*"(:[^"]+)"', settings)
    modules = [inc.lstrip(":").replace(":", os.sep) for inc in includes]
    module_ids = {inc.lstrip(":").replace(":", os.sep): inc.lstrip(":") for inc in includes}
    return modules, module_ids


def module_dependencies(module_dir: str) -> dict[str, list[str]]:
    """configuration -> list of module ids (e.g. 'core:common')."""
    path = os.path.join(ROOT, module_dir, "build.gradle.kts")
    if not os.path.exists(path):
        return {}
    text = read(path)
    deps: dict[str, list[str]] = defaultdict(list)
    for configuration, target in re.findall(
        r'(\w+)\(\s*project\(\s*":([^"]+)"\s*\)\s*\)', text
    ):
        deps[configuration].append(target.replace(":", os.sep))
    return deps


def source_files(module_dir: str, source_set: str) -> list[str]:
    base = os.path.join(ROOT, module_dir, "src", source_set, "java")
    if not os.path.isdir(base):
        base = os.path.join(ROOT, module_dir, "src", source_set, "kotlin")
    if not os.path.isdir(base):
        return []
    out = []
    for dirpath, _dirnames, filenames in os.walk(base):
        for name in sorted(filenames):
            if name.endswith(".kt"):
                out.append(os.path.join(dirpath, name))
    return out


def declarations_in(path: str) -> tuple[str, set[str], set[str]]:
    """(package, candidate FQNs of declared types, candidate FQNs of functions/props)."""
    text = strip_block_comments(read(path))
    package = ""
    types: set[str] = set()
    members: set[str] = set()
    enclosing: list[str] = []
    for raw in text.splitlines():
        line = strip_line_comments(raw)
        if not line.strip():
            continue
        match = PACKAGE_RE.match(line)
        if match and not package:
            package = match.group(1)
            continue
        match = IMPORT_RE.match(line)
        if match:
            continue
        match = DECL_TYPE_RE.match(line)
        if match:
            name = match.group(2)
            prefix = [package] + enclosing
            types.add(".".join(prefix + [name]))
            types.add(f"{package}.{name}")  # importable without the outer qualifier
            enclosing.append(name)
            continue
        match = DECL_TYPEALIAS_RE.match(line)
        if match:
            types.add(f"{package}.{match.group(1)}")
            continue
        for regex in (DECL_FUN_RE, DECL_PROP_RE):
            match = regex.match(line)
            if match:
                name = match.group(2)
                members.add(f"{package}.{name}")
                if enclosing:
                    members.add(".".join([package] + enclosing + [name]))
                break
        # Track closing braces only crudely: good enough to keep `enclosing`
        # bounded; false nesting merely produces *extra* candidate FQNs.
        if line.strip().startswith("}") and enclosing:
            enclosing.pop()
    return package, types, members


def collect_symbols(modules: list[str]) -> tuple[dict[str, set[str]], dict[str, set[str]], dict[str, dict[str, set[str]]]]:
    """type FQN -> modules; member FQN -> modules; module -> files."""
    type_index: dict[str, set[str]] = defaultdict(set)
    member_index: dict[str, set[str]] = defaultdict(set)
    files_by_module: dict[str, dict[str, set[str]]] = {}
    for module in modules:
        main_files = source_files(module, "main")
        files_by_module[module] = {"main": set(main_files)}
        for path in main_files:
            package, types, members = declarations_in(path)
            for t in types:
                type_index[t].add(module)
            for m in members:
                member_index[m].add(module)
    return type_index, member_index, files_by_module


def visible_modules(module: str, deps: dict[str, dict[str, list[str]]], cache: dict[str, set[str]]) -> set[str]:
    """module + everything reachable through api/implementation edges."""
    if module in cache:
        return cache[module]
    seen = {module}
    stack = [module]
    while stack:
        current = stack.pop()
        for configuration, targets in deps.get(current, {}).items():
            for target in targets:
                if target not in seen:
                    seen.add(target)
                    stack.append(target)
    # api-transitive closure: symbols of a module reached through `api` are
    # visible to consumers of that module.
    changed = True
    while changed:
        changed = False
        for member in list(seen):
            for target in deps.get(member, {}).get("api", []):
                if target not in seen:
                    seen.add(target)
                    changed = True
    cache[module] = seen
    return seen


def check_build_files(modules: list[str], problems: list[Problem]) -> dict[str, dict[str, list[str]]]:
    deps: dict[str, dict[str, list[str]]] = {}
    for module in modules:
        directory = os.path.join(ROOT, module)
        build_file = os.path.join(directory, "build.gradle.kts")
        if not os.path.isdir(directory):
            problems.append(Problem("ERROR", module, "module is included in settings.gradle.kts but the directory does not exist"))
            continue
        if not os.path.exists(build_file):
            problems.append(Problem("ERROR", module, "module directory has no build.gradle.kts"))
            continue
        deps[module] = module_dependencies(module)
        text = read(build_file)
        is_application = "android.application" in text or "android-application" in text
        if is_application and ANDROID_MANIFEST_REQUIRED:
            manifest = os.path.join(directory, "src", "main", "AndroidManifest.xml")
            if not os.path.exists(manifest):
                problems.append(Problem("ERROR", module, "Android module is missing src/main/AndroidManifest.xml"))
        for configuration, targets in deps[module].items():
            for target in targets:
                if target not in modules:
                    target_id = target.replace(os.sep, ":")
                    problems.append(Problem(
                        "ERROR",
                        module + "/build.gradle.kts",
                        configuration + " dependency on :" + target_id + " is not included in settings.gradle.kts",
                    ))
    # Modules on disk that are not included in the build.
    settings = read(os.path.join(ROOT, "settings.gradle.kts"))
    for candidate in ("app", "data", "domain", "telegram", "worker"):
        if os.path.isdir(os.path.join(ROOT, candidate)) and f'":{candidate}"' not in settings:
            problems.append(Problem("ERROR", candidate, "directory exists but settings.gradle.kts does not include it"))
    for parent in ("core", "feature"):
        base = os.path.join(ROOT, parent)
        if not os.path.isdir(base):
            continue
        for entry in sorted(os.listdir(base)):
            if os.path.isdir(os.path.join(base, entry)) and f'":{parent}:{entry}"' not in settings:
                problems.append(Problem("ERROR", f"{parent}/{entry}", "directory exists but settings.gradle.kts does not include it"))
    return deps


def check_imports(modules: list[str], deps: dict[str, dict[str, list[str]]], type_index: dict[str, set[str]],
                  member_index: dict[str, set[str]], problems: list[Problem]) -> None:
    visibility_cache: dict[str, set[str]] = {}
    for module in modules:
        visible = visible_modules(module, deps, visibility_cache)
        for source_set in ("main", "debug", "release"):
            for path in source_files(module, source_set):
                text = read(path)
                relative = os.path.relpath(path, ROOT)
                for line in text.splitlines():
                    match = IMPORT_RE.match(line.strip())
                    if not match:
                        continue
                    imported = match.group(1)
                    if not imported.startswith(PROJECT_PACKAGE):
                        continue
                    if imported.endswith(".*"):
                        continue
                    if imported.rsplit(".", 1)[-1] in GENERATED_CLASSES:
                        continue
                    owners = type_index.get(imported) or member_index.get(imported)
                    if not owners:
                        problems.append(Problem("ERROR", relative, f"unresolved project import: {imported}"))
                        continue
                    if not (owners & visible):
                        owner_list = ", ".join(sorted(o.replace(os.sep, ":") for o in owners))
                        problems.append(Problem(
                            "ERROR", relative,
                            f"import {imported} lives in module(s) [{owner_list}] which :{module.replace(os.sep, ':')} does not depend on",
                        ))


INJECTABLE_CONSTRUCTOR_RE = re.compile(
    r"@(?:Inject|AssistedInject)\s+constructor\s*\(([^)]*)\)", re.DOTALL
)
BINDS_RE = re.compile(
    r"abstract\s+fun\s+\w+\(\s*\w+\s*:\s*([A-Za-z0-9_.]+)\s*,?\s*\)\s*:\s*([A-Za-z0-9_.]+)"
)
PROVIDES_RE = re.compile(
    r"@Provides\b[\s\S]{0,220}?(?:suspend\s+)?fun\s+\w+\s*\(([\s\S]*?)\)\s*(?::\s*([A-Za-z0-9_.<>]+))?"
)


def simple_name(fq: str) -> str:
    return fq.rsplit(".", 1)[-1].split("<")[0].replace("?", "")


def split_parameters(signature: str) -> list[str]:
    """Splits a constructor signature on top-level commas (generics aware)."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for char in signature:
        if char == "<":
            depth += 1
        elif char == ">":
            depth -= 1
        if char == "," and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(char)
    if "".join(current).strip():
        parts.append("".join(current))
    return [part.strip() for part in parts if part.strip()]


def parameter_type(parameter: str) -> tuple[str | None, bool]:
    """(type simple name, is_assisted) for one constructor parameter."""
    assisted = "@Assisted" in parameter
    cleaned = re.sub(r"@\w+(?:\([^)]*\))?", "", parameter).strip()
    cleaned = re.sub(r"^(private|internal|protected|public|val|var|crossinline|noinline)\s+", "", cleaned)
    cleaned = re.sub(r"^(val|var)\s+", "", cleaned)
    match = re.match(r"^\w+\s*:\s*([A-Za-z0-9_.<>?]+)", cleaned)
    if not match:
        return None, assisted
    return simple_name(match.group(1)), assisted


def check_hilt(modules: list[str], type_index: dict[str, set[str]], problems: list[Problem]) -> None:
    """
    Static Hilt graph sanity check.

    Only parameters of Dagger-managed constructors (`@Inject` / `@AssistedInject`)
    are considered, and only types declared in this repository — framework types
    (Context, SharedPreferences, NotificationManager, …) are provided by Hilt's
    Android support or constructed by hand.

    A project type used as a dependency must be either an interface/abstract type
    bound by @Binds or @Provides, a class with an @Inject constructor, or the
    return type of a @Provides function. Anything else fails the Dagger build,
    so it is reported as an error here.
    """
    project_types: set[str] = {simple_name(fq) for fq in type_index}
    interfaces: set[str] = set()
    inject_constructors: set[str] = set()
    bound: set[str] = set()
    provided: set[str] = set()
    required: dict[str, list[str]] = defaultdict(list)

    for module in modules:
        for path in source_files(module, "main"):
            text = strip_block_comments(read(path))
            relative = os.path.relpath(path, ROOT)

            for match in DECL_TYPE_RE.finditer(text):
                if match.group(1) == "interface":
                    interfaces.add(match.group(2))

            # A class is Dagger-constructible only when *its own* declaration is
            # followed by an @Inject constructor (not merely another class in the file).
            for name in re.findall(
                r"\bclass\s+(\w+)(?:(?!\bclass\b)[\s\S]){0,200}?@Inject\s+constructor", text
            ):
                inject_constructors.add(name)

            for impl, interface in BINDS_RE.findall(text):
                bound.add(simple_name(interface))
                if simple_name(impl) not in project_types:
                    problems.append(Problem("ERROR", relative, f"@Binds implementation type not found: {impl}"))

            for signature, return_type in PROVIDES_RE.findall(text):
                if return_type:
                    provided.add(simple_name(return_type))

            for signature in INJECTABLE_CONSTRUCTOR_RE.findall(text):
                for parameter in split_parameters(signature):
                    name, assisted = parameter_type(parameter)
                    if assisted or name is None or name not in project_types:
                        continue
                    required[name].append(relative)

    for name, usages in sorted(required.items()):
        if name in inject_constructors or name in provided or name in bound:
            continue
        kind = "interface" if name in interfaces else "type"
        problems.append(Problem(
            "ERROR", usages[0],
            f"`{name}` ({kind}) is required by Dagger in {len(usages)} place(s) "
            f"but no @Binds/@Provides/@Inject constructor produces it",
        ))


def check_unused_imports(modules: list[str], problems: list[Problem]) -> None:
    """Flags imports whose simple name never appears again in the file.

    Kotlin treats unused imports as warnings; this project's rule is that
    warnings must not accumulate (specification §76), so they are surfaced here.
    """
    for module in modules:
        for source_set in ("main", "debug", "release"):
            for path in source_files(module, source_set):
                text = read(path)
                relative = os.path.relpath(path, ROOT)
                body_start = 0
                imports: list[tuple[int, str, str]] = []
                for index, line in enumerate(text.splitlines(), start=1):
                    match = IMPORT_RE.match(line.strip())
                    if match:
                        imported = match.group(1)
                        imports.append((index, imported, simple_name(imported)))
                        body_start = max(body_start, index)
                if not imports:
                    continue
                body = "\n".join(text.splitlines()[body_start:])
                for line_number, imported, name in imports:
                    if imported.endswith(".*"):
                        continue
                    if name in GENERATED_CLASSES or name in IMPLICIT_IMPORTS:
                        continue
                    # Annotations like @Composable appear as `@Name`; operators
                    # such as `plus` may be implicit, so only whole-word usage counts.
                    if not re.search(r"(?<![A-Za-z0-9_])" + re.escape(name) + r"(?![A-Za-z0-9_])", body):
                        problems.append(Problem(
                            "WARN", f"{relative}:{line_number}", f"unused import: {imported}",
                        ))


TRIPLE_QUOTED_RE = re.compile(r'''"""[\s\S]*?"""''')
SINGLE_LINE_STRING_RE = re.compile(r'''"(?:\\.|[^"\\\n])*"''')
# `Name.` — a qualified reference (companion member, nested type, enum entry).
QUALIFIED_USE_RE = re.compile(r"(?<![A-Za-z0-9_.$@])([A-Z][A-Za-z0-9_]*)\s*\.")
# `Name(` — a constructor / composable / function-style call.
CALL_USE_RE = re.compile(r"(?<![A-Za-z0-9_.$@])([A-Z][A-Za-z0-9_]*)\s*\(")
# `Name::class` — a class-literal reference.
CLASS_REF_RE = re.compile(r"(?<![A-Za-z0-9_.$@])([A-Z][A-Za-z0-9_]*)\s*::")
# `Name<`, `Name>`, `Name?`, `Name,`, `Name)`, `Name]` — type-argument positions.
TYPE_ARG_RE = re.compile(r"(?<![A-Za-z0-9_.$@])([A-Z][A-Za-z0-9_]*)(?=\s*[<>?,)\]])")
# `: Name` — parameter, property and return type positions.
ANNOTATED_TYPE_RE = re.compile(r"(?<![A-Za-z0-9_]):\s*([A-Z][A-Za-z0-9_]*)")


def strip_strings(text: str) -> str:
    """Removes string literals so their contents cannot look like code."""
    return SINGLE_LINE_STRING_RE.sub('''""''', TRIPLE_QUOTED_RE.sub('''""''', text))


def file_imports(text: str) -> tuple[set[str], set[str], list[str]]:
    """(imported simple names, imported FQNs, wildcard package prefixes)."""
    simples: set[str] = set()
    fqns: set[str] = set()
    wildcards: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line.startswith("import "):
            continue
        body = line[len("import "):].strip()
        alias = None
        if " as " in body:
            body, alias = [part.strip() for part in body.split(" as ", 1)]
        fqns.add(body)
        if body.endswith(".*"):
            wildcards.append(body[:-2])
        else:
            simples.add(alias or simple_name(body))
    return simples, fqns, wildcards


def check_missing_imports(
    modules: list[str],
    type_index: dict[str, set[str]],
    problems: list[Problem],
) -> None:
    """Flags references to *project* types that the file never imports.

    Kotlin resolves an unqualified name only through the same package or an
    import, so `AppError.ValidationError(...)` in a file that does not import
    `AppError` is a compile error. The offline harness catches this for the
    JVM-only modules; this check covers every module, including the Android and
    Compose ones that cannot be type-checked without an SDK. Only names that are
    declared somewhere in this repository are considered, so stdlib, Android and
    Compose symbols are never flagged.
    """
    simple_index: dict[str, set[str]] = defaultdict(set)
    for fqn in type_index:
        simple_index[simple_name(fqn)].add(fqn)

    for module in modules:
        for source_set in ("main", "debug", "release", "test", "androidTest", "testDebug"):
            for path in source_files(module, source_set):
                text = strip_strings(strip_block_comments(read(path)))
                relative = os.path.relpath(path, ROOT)
                package, declared, _members = declarations_in(path)
                local_names = {simple_name(fqn) for fqn in declared}
                imported_simples, imported_fqns, wildcards = file_imports(text)

                for line_number, raw in enumerate(text.splitlines(), start=1):
                    line = strip_line_comments(raw)
                    if not line.strip() or line.strip().startswith("import "):
                        continue
                    used: set[str] = set()
                    for pattern in (QUALIFIED_USE_RE, CALL_USE_RE, CLASS_REF_RE,
                                    TYPE_ARG_RE, ANNOTATED_TYPE_RE):
                        used.update(pattern.findall(line))
                    for name in sorted(used):
                        if name in GENERATED_CLASSES or name in IMPLICIT_IMPORTS:
                            continue
                        candidates = simple_index.get(name)
                        if not candidates or name in local_names or name in imported_simples:
                            continue
                        packages = {fqn.rsplit(".", 1)[0] for fqn in candidates}
                        if package in packages:
                            continue  # same-package visibility
                        if any(fqn in imported_fqns for fqn in candidates):
                            continue
                        if any(wildcard in packages for wildcard in wildcards):
                            continue
                        target = sorted(candidates)[0]
                        problems.append(Problem(
                            "ERROR",
                            f"{relative}:{line_number}",
                            f"missing import for project type {name} "
                            f"(add: import {target})",
                        ))


def check_banned(modules: list[str], problems: list[Problem]) -> None:
    for module in modules:
        for source_set in ("main",):
            for path in source_files(module, source_set):
                text = read(path)
                relative = os.path.relpath(path, ROOT)
                for line_number, raw in enumerate(text.splitlines(), start=1):
                    line = strip_line_comments(raw)
                    for pattern, message in BANNED_PATTERNS:
                        if re.search(pattern, line, flags=re.IGNORECASE):
                            problems.append(Problem("ERROR", f"{relative}:{line_number}", message))


def check_icons(modules: list[str], problems: list[Problem]) -> None:
    """Icons must be allowlisted: new ones need a deliberate review."""
    if not os.path.exists(ICONS_ALLOWLIST):
        problems.append(Problem("ERROR", "tools/verify/icons-allowlist.txt", "icon allowlist is missing"))
        return
    allowed: set[str] = set()
    for raw in read(ICONS_ALLOWLIST).splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            allowed.add(line)
    # Handles both `Icons.Filled.X` and `Icons.AutoMirrored.Filled.X`.
    pattern = re.compile(r"Icons\.((?:AutoMirrored\.)?[A-Za-z]+)\.([A-Za-z0-9_]+)")
    for module in modules:
        for path in source_files(module, "main"):
            text = read(path)
            if "Icons." not in text:
                continue
            relative = os.path.relpath(path, ROOT)
            for line_number, raw_line in enumerate(text.splitlines(), start=1):
                line = strip_line_comments(raw_line)
                for style, name in pattern.findall(line):
                    entry = style + "." + name
                    if entry not in allowed:
                        problems.append(Problem(
                            "ERROR",
                            relative + ":" + str(line_number),
                            "icon Icons." + entry + " is not listed in tools/verify/icons-allowlist.txt",
                        ))


def check_required_files(problems: list[Problem]) -> None:
    for relative in REQUIRED_FILES:
        if not os.path.exists(os.path.join(ROOT, relative)):
            problems.append(Problem("ERROR", relative, "required file is missing"))


def check_catalog(problems: list[Problem]) -> None:
    """Every module must take dependency versions from the version catalog only."""
    modules, _ids = parse_modules()
    catalog = read(os.path.join(ROOT, "gradle", "libs.versions.toml"))
    declared_aliases = set(re.findall(r"^([a-z0-9\-]+)\s*=\s*\{", catalog, flags=re.MULTILINE))
    for module in modules:
        path = os.path.join(ROOT, module, "build.gradle.kts")
        if not os.path.exists(path):
            continue
        text = read(path)
        relative = os.path.relpath(path, ROOT)
        for group, name, version in re.findall(r'"([a-z0-9.\-]+):([a-z0-9.\-]+):([0-9][^"]*)"', text):
            problems.append(Problem("ERROR", relative, f"hard-coded dependency version {group}:{name}:{version} — pin it in gradle/libs.versions.toml"))
        for alias in re.findall(r"libs\.([a-z0-9.\-]+)", text):
            normalized = alias.replace(".", "-")
            if normalized not in declared_aliases and not normalized.startswith("versions") and not normalized.startswith("plugins"):
                problems.append(Problem("ERROR", relative, f"unknown version-catalog alias: libs.{alias}"))


def fix_unused_imports(modules: list[str]) -> int:
    """Removes imports that are never referenced (see check_unused_imports)."""
    removed = 0
    for module in modules:
        for source_set in ("main", "debug", "release", "test", "androidTest"):
            for path in source_files(module, source_set):
                text = read(path)
                lines = text.splitlines()
                import_lines = [i for i, l in enumerate(lines) if IMPORT_RE.match(l.strip())]
                if not import_lines:
                    continue
                body_start = max(import_lines) + 1
                body = "\n".join(lines[body_start:])
                drop: set[int] = set()
                for index in import_lines:
                    match = IMPORT_RE.match(lines[index].strip())
                    if not match:
                        continue
                    imported = match.group(1)
                    name = simple_name(imported)
                    if imported.endswith(".*") or name in GENERATED_CLASSES or name in IMPLICIT_IMPORTS:
                        continue
                    if not re.search(r"(?<![A-Za-z0-9_])" + re.escape(name) + r"(?![A-Za-z0-9_])", body):
                        drop.add(index)
                if drop:
                    kept = [line for i, line in enumerate(lines) if i not in drop]
                    with open(path, "w", encoding="utf-8") as handle:
                        handle.write("\n".join(kept) + "\n")
                    removed += len(drop)
    return removed


def main() -> int:
    if "--fix-unused-imports" in sys.argv:
        modules, _ids = parse_modules()
        count = fix_unused_imports(modules)
        print(f"removed {count} unused import(s)")
        return 0

    problems: list[Problem] = []
    modules, _ids = parse_modules()
    deps = check_build_files(modules, problems)
    type_index, member_index, _files = collect_symbols(modules)
    check_imports(modules, deps, type_index, member_index, problems)
    check_hilt(modules, type_index, problems)
    check_missing_imports(modules, type_index, problems)
    check_unused_imports(modules, problems)
    check_banned(modules, problems)
    check_required_files(problems)
    check_catalog(problems)
    check_icons(modules, problems)

    errors = [p for p in problems if p.severity == "ERROR"]
    warnings = [p for p in problems if p.severity == "WARN"]

    print()
    print("═" * 56)
    print(f" structure-check: {len(modules)} modules, "
          f"{sum(len(v) for v in type_index.values())} declared types")
    print("═" * 56)
    for problem in errors:
        print(f"  ✗ {problem}")
    for problem in warnings:
        print(f"  ! {problem}")
    print(f"  → {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
